steps:
  - uses: actions/checkout@v1.0
    name: Check out code

  - name: Docker Build & Push
    uses: mr-smithers-excellent/docker-build-push@v3.1
    with:
      image: jonjozwiak/checkov-rt
      tag: latest
      registry: docker.io
      dockerfile: Dockerfile
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}